* v1.0.0
  This is a *Breaking Change* upgrade. I've made the following major
  changes:
  - Move to ~el-get~ as the package management system.
  - Enable development against Clojure versions 1.6 and below (Find
    instructions in the ~README.org~ file).
  - Make Emacs 25 the minimum supported Emacs version.

  To upgrade your ~emacs-up~, *delete your original installation* and
  clone this repository from scratch. Follow the updated setup
  instructions in the ~README.org~ file.

* v0.1.0
  This initial version of ~emacs-up~ is built around ~package.el~
  which is the default package management system for Emacs.

  However, a number of people within Helpshift are working on projects
  which need to support Clojure versions below 1.7 (eg: projects which
  depend on the Storm framework). Versions of CIDER - The Clojure
  Interactive Development Environment that Rocks - which are available
  in public package repositories do not support these older Clojure
  versions.

  Future development of ~emacs-up~ will move to ~el-get~, which allows
  the developers to pin the version of the emacs package that they
  want to install.
