* Introduction
  ~emacs-up~ is a bare-bones, quick-start Emacs configuration. It is
  meant to get newcomers started and productive with Emacs and
  contains the minimal configuration required to satisfy employee asks
  inside Helpshift. ~emacs-up~ is currently configured for Clojure
  programming only, but I'm hoping that it will soon be expanded to
  include other programming languages used within Helpshift.

* Installation
  - The minimum supported version for this configuration is Emacs
    24.4. I recommend that you use Emacs 25 with this configuration.
    You can install Emacs 25 through brew as follows:
    #+begin_example
      $ brew install emacs --devel
    #+end_example
  - Clone ~emacs-up~ to your machine as your ~.emacs.d~ folder.
    #+begin_example
      $ git clone https://github.com/helpshift/emacs-up.git ~/.emacs.d
    #+end_example
  - Fire up Emacs and wait for it to download packages (This is a
    one-time thing).
  - (For beginners) Go through the tutorial in the ~docs/~ folder to
    get started.

* Happy Programming! May the force be with you.
